name: release
on:
  release:
    types: [created]

jobs:

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v6
      - name: Set VERSION env
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1.55
        with:
          github_token: ${{ secrets.PNG2ASM_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.25.5"
          pre_command: export CGO_ENABLED=0
          build_flags: -v
          ldflags: -X 'main.version=${{env.VERSION}}' -X 'main.gitCommit=${{ github.sha }}'
          extra_files: LICENSE README.md
          retry: 10

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set VERSION env
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VERSION: ${{ env.VERSION }}
          GIT_COMMIT: ${{ github.sha }}
        with:
          name: laghoule/png2asm
          username: ${{ github.actor }}
          password: ${{ secrets.png2asm_TOKEN }}
          buildargs: VERSION, GIT_COMMIT
          registry: ghcr.io
          tags: "latest,${{ env.VERSION }}"
          tag_semver: true
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VERSION: ${{ env.VERSION }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
        with:
          name: laghoule/png2asm
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildargs: VERSION, GIT_COMMIT
          tags: "latest,${{ env.VERSION }}"
          tag_semver: true
